project:
  type: book
  output-dir: _book

book:
  title: "A Little Book of Bioinformatics"
  reader-mode: true
  
  cover-image: assets/images/cover.png
  favicon: assets/images/cover.png
  
  page-footer:
    left: |
      This book was written by Leighton Pritchard.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.  
  
  repo-url: https://github.com/sipbs-compbiol/little-bioinformatics-book
  repo-branch: main
  repo-actions: [edit, issue]
  
  author: "Leighton Pritchard"
  date: "2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    
    - part: representing_biological_data.qmd
    
    - part: biological_databases.qmd
    
    - part: pairwise_sequence_alignment.qmd

    - part: multiple_sequence_alignment.qmd
      chapters: 
        - mafft.qmd
    
    - part: biological_networks.qmd
    
    - part: biological_structures.qmd
    
    - part: signatures_of_evolution.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    
    author-meta: "Leighton Pritchard"
    callout-appearance: simple
    
  pdf:
    documentclass: scrreprt



